name: CI-CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Burası 'backend' klasörüne git demek
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Go 
        uses: actions/setup-go@v5
        with: 
          go-version: '1.22' # İki noktadan sonra boşluk var!

      - name: Install Dependencies
        run: go mod download

      - name: Build Check 
        run: go build -v ./...